[workspace]
authors = ["Frank Martinez <mnesarco@gmail.com>"]
channels = ["conda-forge"]
name = "marzpyb"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
clang = ">=21.1.2,<22"
ninja = ">=1.13.1,<2"
cmake = ">=4.1.1,<5"
python = ">=3.13.7,<3.14"
clang-tools = ">=21.1.2,<22"
libstdcxx-devel_linux-64 = ">=15.1.0,<16"
lldb = ">=21.1.0,<22"
